const swaggerUi = require('swagger-ui-express');
const swaggerJSDoc = require('swagger-jsdoc');

// const options = {
//   swaggerDefinition: {
//     // Like the one described here: https://swagger.io/specification/#infoObject
//     info: {
//       title: 'Test API',
//       version: '1.0.0',
//       description: 'Test Express API with autogenerated swagger doc',
//     },
//   },
//   // List of files to be processes. You can also set globs './routes/*.js'
//   apis: ['./routes/*.js'],
// };

// const specs = swaggerJsdoc(options);

// swagger definition
var swaggerDefinition = {
  info: {
    title: 'Node Swagger API',
    version: '1.0.0',
    description: 'Demonstrating how to describe a RESTful API with Swagger',
  },
  host: 'localhost:3000',
  basePath: '/',
};

// options for the swagger docs
var options = {
  // import swaggerDefinitions
  swaggerDefinition: swaggerDefinition,
  // path to the API docs
  apis: ['./routes/*.js'],
};

// initialize swagger-jsdoc
var swaggerSpec = swaggerJSDoc(options);

module.exports = (app) =>{
  app.get('/swagger.json', function(req, res) {
    res.setHeader('Content-Type', 'application/json');
    res.send(swaggerSpec);
  });
    // app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
}